# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContainerModel', '0002_container_list_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='container_list',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
