# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContainerModel', '0003_container_list_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='container_list',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
