# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContainerModel', '0004_container_list_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='container_list',
            name='show_type',
            field=models.IntegerField(default=0),
        ),
    ]
